name = "inpinity-rpc-proxy"
main = "src/index.ts"
compatibility_date = "2024-11-21"
account_id = "ee57d3036a25f352ab089a94066a03c1"

[vars]
UPSTREAM_RPC = "https://api.mainnet-beta.solana.com"
BACKUP_RPC = "https://solana.publicnode.com"
ALLOWED_ORIGINS = "https://inpinity.online,https://mint.inpinity.online,https://inpinity-mint.pages.dev,https://inpinity-mint.pages.dev/mint“
REMOTE_CLAIMS_URL = ""
[[kv_namespaces]]
binding = "CLAIMS"
id = "139ec0627b02429db4507c14b5a3a1fd"

[site]
bucket = "./mint"